### ISSUE TITLE
运行·pre_train报错，TypeError: Accelerator.__init__() got an unexpected keyword argument 'use_seedable_sampler'

### ISSUE THREAD

**Issue by JaymzWang** [charent/ChatLM-mini-Chinese#31]
E:\ChatLM-mini-Chinese\ChatLM-mini-Chinese\venv\Scripts\python.exe E:\ChatLM-mini-Chinese\ChatLM-mini-Chinese\pre_train.py 
Traceback (most recent call last):
  File "E:\ChatLM-mini-Chinese\ChatLM-mini-Chinese\pre_train.py", line 136, in <module>
    pre_train(config)
  File "E:\ChatLM-mini-Chinese\ChatLM-mini-Chinese\pre_train.py", line 109, in pre_train
    trainer = Seq2SeqTrainer(
              ^^^^^^^^^^^^^^^
  File "E:\ChatLM-mini-Chinese\ChatLM-mini-Chinese\venv\Lib\site-packages\transformers\trainer_seq2seq.py", line 56, in __init__
    super().__init__(
  File "E:\ChatLM-mini-Chinese\ChatLM-mini-Chinese\venv\Lib\site-packages\transformers\trainer.py", line 367, in __init__
    self.create_accelerator_and_postprocess()
  File "E:\ChatLM-mini-Chinese\ChatLM-mini-Chinese\venv\Lib\site-packages\transformers\trainer.py", line 4127, in create_accelerator_and_postprocess
    self.accelerator = Accelerator(
                       ^^^^^^^^^^^^
TypeError: Accelerator.__init__() got an unexpected keyword argument 'use_seedable_sampler'

Process finished with exit code 1

**Comment by charent** [comment]
检查一下你的`transformers`版本，`4.36.0`和`4.37.2`都没问题，还有`accelerate`版本。
