### ISSUE TITLE
项目怎么使用fastchat 进行调试

### ISSUE THREAD

**Issue by zhilangtaosha** [charent/ChatLM-mini-Chinese#33]
直接加载有问题，不知道怎么处理

(sdw) PS F:\VM> python -m fastchat.serve.model_worker --model-path ChatLM-mini-Chinese
2024-02-29 16:50:15 | INFO | model_worker | args: Namespace(host='localhost', port=21002, worker_address='http://localhost:21002', controller_address='http://localhost:21001', model_path='ChatLM-mini-Chinese', revision='main', device='cuda', gpus=None, num_gpus=1, max_gpu_memory=None, dtype=None, load_8bit=False, cpu_offloading=False, gptq_ckpt=None, gptq_wbits=16, gptq_groupsize=-1, gptq_act_order=False, awq_ckpt=None, awq_wbits=16, awq_groupsize=-1, enable_exllama=False, exllama_max_seq_len=4096, exllama_gpu_split=None, exllama_cache_8bit=False, enable_xft=False, xft_max_seq_len=4096, xft_dtype=None, model_names=None, conv_template=None, embed_in_truncate=False, limit_worker_concurrency=5, stream_interval=2, no_register=False, seed=None, debug=False, ssl=False)
2024-02-29 16:50:15 | INFO | model_worker | Loading the model ['ChatLM-mini-Chinese'] on worker 43282e2a ...
2024-02-29 16:50:15 | ERROR | stderr | Traceback (most recent call last):
2024-02-29 16:50:15 | ERROR | stderr |   File "C:\ProgramData\anaconda3\envs\sdw\lib\runpy.py", line 196, in _run_module_as_main
2024-02-29 16:50:15 | ERROR | stderr |     return _run_code(code, main_globals, None,
2024-02-29 16:50:15 | ERROR | stderr |   File "C:\ProgramData\anaconda3\envs\sdw\lib\runpy.py", line 86, in _run_code
2024-02-29 16:50:15 | ERROR | stderr |     exec(code, run_globals)
2024-02-29 16:50:15 | ERROR | stderr |   File "C:\ProgramData\anaconda3\envs\sdw\lib\site-packages\fastchat\serve\model_worker.py", line 414, in <module>
2024-02-29 16:50:15 | ERROR | stderr |     args, worker = create_model_worker()
2024-02-29 16:50:15 | ERROR | stderr |   File "C:\ProgramData\anaconda3\envs\sdw\lib\site-packages\fastchat\serve\model_worker.py", line 385, in create_model_worker
2024-02-29 16:50:15 | ERROR | stderr |     worker = ModelWorker(
2024-02-29 16:50:15 | ERROR | stderr |   File "C:\ProgramData\anaconda3\envs\sdw\lib\site-packages\fastchat\serve\model_worker.py", line 77, in __init__
2024-02-29 16:50:15 | ERROR | stderr |     self.model, self.tokenizer = load_model(
2024-02-29 16:50:15 | ERROR | stderr |   File "C:\ProgramData\anaconda3\envs\sdw\lib\site-packages\fastchat\model\model_adapter.py", line 353, in load_model
2024-02-29 16:50:15 | ERROR | stderr |     model, tokenizer = adapter.load_model(model_path, kwargs)
2024-02-29 16:50:15 | ERROR | stderr |   File "C:\ProgramData\anaconda3\envs\sdw\lib\site-packages\fastchat\model\model_adapter.py", line 99, in load_model
2024-02-29 16:50:15 | ERROR | stderr |     model = AutoModelForCausalLM.from_pretrained(
2024-02-29 16:50:15 | ERROR | stderr |   File "C:\ProgramData\anaconda3\envs\sdw\lib\site-packages\transformers\models\auto\auto_factory.py", line 564, in from_pretrained
2024-02-29 16:50:15 | ERROR | stderr |     raise ValueError(
2024-02-29 16:50:15 | ERROR | stderr | ValueError: Unrecognized configuration class <class 'transformers.models.t5.configuration_t5.T5Config'> for this kind of AutoModel: AutoModelForCausalLM.
2024-02-29 16:50:15 | ERROR | stderr | Model type should be one of BartConfig, BertConfig, BertGenerationConfig, BigBirdConfig, BigBirdPegasusConfig, BioGptConfig, BlenderbotConfig, BlenderbotSmallConfig, BloomConfig, CamembertConfig, LlamaConfig, CodeGenConfig, CpmAntConfig, CTRLConfig, Data2VecTextConfig, ElectraConfig, ErnieConfig, FalconConfig, FuyuConfig, GemmaConfig, GitConfig, GPT2Config, GPT2Config, GPTBigCodeConfig, GPTNeoConfig, GPTNeoXConfig, GPTNeoXJapaneseConfig, GPTJConfig, LlamaConfig, MarianConfig, MBartConfig, MegaConfig, MegatronBertConfig, MistralConfig, MixtralConfig, MptConfig, MusicgenConfig, MvpConfig, OpenLlamaConfig, OpenAIGPTConfig, OPTConfig, PegasusConfig, PersimmonConfig, PhiConfig, PLBartConfig, ProphetNetConfig, QDQBertConfig, Qwen2Config, ReformerConfig, RemBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, RwkvConfig, Speech2Text2Config, StableLmConfig, TransfoXLConfig, TrOCRConfig, WhisperConfig, XGLMConfig, XLMConfig, XLMProphetNetConfig, XLMRobertaConfig, XLMRobertaXLConfig, XLNetConfig, XmodConfig.

**Comment by charent** [comment]
fastchat不支持T5模型
